using System;
namespace OptimizingLastMile.Models.Commons;

public enum ErrorCodeEnum
{
    // Auth
    USERNAME_NOT_EXIST,
    PASSWORD_NOT_CORRECT,
    ACCOUNT_IS_DISABLE,
    ACCOUNT_REJECTED,
    ACCOUNT_ALREADY_EXIST,
    ROLE_NOT_ALLOW_RESGISTER_BY_USERNAME,

    // Error on AccountProfile
    INVALID_BIRTHDAY,
    DRIVER_HAVE_ORDER,
    MANAGER_HAVE_ORDER,
    CUSTOMER_HAVE_ORDER,

    // Order
    INVALID_OWNER,
    INVALID_DRIVER,
    NOT_ALLOW_UPDATE_FOR_CURRENT_STATUS,
    NOT_ALLOW_DELETE_FOR_CURRENT_STATUS,
    NOT_ALLOW_FEEDBACK,
    ROLE_NOT_ALLOW_UPDATE_THIS_STATUS,
    INVALID_UPDATE_ORDER_STATUS,

    // Common
    METHOD_NOT_ALLOW,
    UNKNOWN_ERROR,
    FEATURE_LOCK,

    // OTP
    TOO_MANY_REQUEST_OTP,
    TOO_MANY_VERIFY_OTP,
    VERIFY_OTP_TIME_OUT,
    VERIFICATION_CODE_INCORRECT,

    // Firebase
    INVALID_TOKEN_FIREBASE
}

